version: '3.8'

services:
  live-transcript-service-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: live-transcript-service-dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3003/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - transcript-network-dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  transcript-network-dev:
    driver: bridge