version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: live-transcript-service-dev
    command: npm run dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - transcript_network

networks:
  transcript_network:
    driver: bridge